### ISSUE TITLE
Deprecate Mento V1 web app

### ISSUE THREAD

**Issue by philbow61** [mento-protocol/mento-web#105]
### Description
We want to deprecate the old [Mento V1 DApp](https://mento.finance).

### Acceptance Criteria
- [x] https://mento.finance (v1) now redirects to https://app.mento.org (v2)
- [x] Potential 3rd Party Services have been disabled (i.e. analytics, sentry)
   - **UPDATE PP: There are no 3rd party services to disable (checked sentry, no analytics found)**
- [x] Victoria has been informed about takedown ahead of time so she can coordinate potential social media announcements
- [x] Rossy has been informed
- [x] https://app.mento.org no longer displays V2 banner
- [x] Remove mento.finance from [Regression Test Steps](https://www.notion.so/Mento-Web-App-Regression-Tests-37bd43a7da8d4e38b65993320a33d557)
- [x] [Last v1 commit](https://github.com/mento-protocol/mento-web/commit/664ac137ac116aa68ab7120d61a00dc70cbfe4e6) has been git-tagged with `v1.5.2`
- [x] `production-v1` branch in mento-web has been deleted
- [x] `production-v2` branch in mento-web has been deleted

### How To Test

Check PR branch here that banner is gone and app still works https://mento-web-git-feat-remove-v2-banner-mentolabs.vercel.app/

**Comment by chapati23** [comment]
Updated ACs after Discord discussion:

**Acceptance Criteria:**

- [] MU04 has passed (which formally deprecates v1)
- []  There is a redirect from mento.finance (v1) => app.mento.org (v2)
- []  Mento V1 web app at https://mento.finance is taken offline
- []  Potential 3rd Party Services have been disabled (i.e. analytics, sentry)
- []  Victoria has been informed about takedown ahead of time so she can coordinate potential social media announcements
- []  Last v1 commit has been git-tagged with v1.5.2
- []  production-v1 branch in mento-web has been deleted

**Comment by chapati23** [comment]
mento.finance domain is owned by @bowd

**Comment by chapati23** [comment]
After talking to Bayo, we agreed don't need to wait til MU04 passing with the redirect

**Comment by bayological** [comment]
@chapati23 We should also ping Rossy so he can shut down the old project. Also as part of this we should remove the V2 banner on app.mento.org.

**Comment by chapati23** [comment]
I have tagged the latest commit of the `production-v1` branch with `v1.5.2` and then deleted the branch

**Comment by chapati23** [comment]
Ready for review https://mento-web-git-feat-remove-v2-banner-mentolabs.vercel.app/
