### ISSUE TITLE
Add newsletter sign up form to mento.org

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/mento-web#113]
**Description**

We need to add a subscription component to the website that allows users to sign up for Mento Magazine. This component will be integrated with Mailchimp to manage and store subscriber information. The setup for the Mailchimp integration will be handled by @olenovyk.

The design details for the subscription component can be found here: [Designs on Figma](https://www.figma.com/file/oruRGuRVHXmMCFCWJwPQLU/MENTO-Website-Illustrations?type=design&node-id=4371%3A210&mode=design&t=aRQtZeFFePQWVWJh-1)

The component will have a two-step interaction:

1. Initial Call-to-Action (CTA): Display an 'open envelope' graphic alongside a prompt for the user to enter their email address to sign up.
2. Confirmation State: After successful subscription, show a 'closed envelope' graphic and a thank you message.

**Acceptance criteria**
- [ ] There is a text input field for users to enter their email addresses.
- [ ] A 'Subscribe' button is present next to the input field.
- [ ] Clicking the 'Subscribe' button triggers the subscription process.
- [ ] On clicking 'Subscribe', if the email is in a valid format, the user's email is sent to Mailchimp.
- [ ] After a successful subscription, the component transitions to display a 'Thank you' message with a 'closed envelope' graphic.
- [ ] If the subscription is unsuccessful (e.g., due to network issues), the user is notified with an error message.
- [ ] Email input is validated for proper format and an error message is displayed for invalid entries.

**Comment by bayological** [comment]
@olenovyk Vercel analytics to track sign-ups does not make sense. We will know someone has signed up as the Mailchimp list or audience would have increased. I'm also sure they have analytics in there, including open rates etc..

**Comment by olenovyk** [comment]
It does make sense. You want to link email sign up to other data you have in vercel. You want to know where form the perosn came to the site, which pages they visited. Not just number of sign ups in isolation.

**Comment by RyRy79261** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/wdF5Cdz9K0/estimate/4) in Sprint Poker #​​19

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by bayological** [comment]
@RyRy79261 I just chatted with @olenovyk and his recommendation is to archive this issue as this will be covered in the site rebrand work.
