### ISSUE TITLE
Provide feedback in UI when trading limits have been reached

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/mento-web#126]
## Description
In the past users have contacted us about not being able to swap and often times the cause of this that trading limits have been reached. This issue is to add some error handling for cases when trading limits have been reach (or any other error which can be deduced from SDK errors), and provide feedback to users in these scenarios.

_for additional context_
This was inspired by an [issue an SDK user experienced ](https://github.com/mento-protocol/mento-sdk/issues/32)

## Action Items
- [ ] Add error handling to detect when trading limits have been reached or pools are empty using the Mento SDK
- [ ] Provide some feedback to users in the form of an error message on the UI either of these cases

## Acceptance Criteria
- [ ] Error handling in introduced for when trading limits have been reached
- [ ] (optional) Error handling introduced for similar cases which can be deduced from SDK
- [ ] Feedback is added to the UI when these errors occur

**Comment by RyRy79261** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/w25ulrgbCg/estimate/2) in Sprint Poker #​​18

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
