### ISSUE TITLE
Product usage dashboard

### ISSUE THREAD

**Issue by ole-nov** [mento-protocol/mento-web#31]
**Description**
All metrics should be visualized as daily line graphs if no conflicting requirements are provided for a particular metric. 

Each stable asset should be reported separately, there should be a dropdown/toggle to switch between them. 

All reports are denominated in $ USD if not stated otherwise.

**Product usage metrics (per stablecoin)**

Marketcap

Daily trading volume 

Velocity (market cap/daily volume)

Transactions per day

Transactions per wallet per day

Daily mint/burn ratio

**Acceptance criteria**

- [x]  There is a dashboard in Makerdojo with specified above metrics for each of the stable assets.

**Comment by philbow61** [comment]
https://makerdojo.io/dashboards/106-stable-dashboard?p_end_date=d_now&p_start_date=2022-12-01&p_token=%270x765DE816845861e75A25fCA122bb6898B8B1282a%27
