### ISSUE TITLE
BUG: Swapping tokens using wallet connect does not work (mobile & desktop)

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-web#49]
**Description**
When attempting to swap tokens using an account connected to the site with WalletConnect swaps fail with the message "unable to complete swap"

**Steps To Reproduce** 

**Expected Result**

**Actual Result**

**Additional Info**

**Comment by jmrossy** [comment]
Hmm, this may be due to an issue in the `react-celo` lib it's using. I'll investigate

**Comment by bayological** [comment]
> Hmm, this may be due to an issue in the `react-celo` lib it's using. I'll investigate. @bayological what wallet were you connecting to? Because compat between DApp WC version and wallet WC version is also a factor.

@jmrossy  Sorry, I didn't get round to adding more info to the issue. I replicated this issue using TrustWallet on a mobile device using the in-app browser, however, it's also an issue when connecting to the site on a desktop/laptop using wallet connect and Metamask mobile.

**Comment by jmrossy** [comment]
The likely cause is that WC v1 is being sunsetted so wallet are finally moving over to WC v2. 
I see @nicolasbrugneaux has already converted react-celo to WC v2 in react-celo v5+, which is great. I'll update react-celo here shortly.

Note @bayological there will likely a transition period where some wallets keep using WC v1. Updating will break compat with those for a while but long-term this is a necessary upgrade

**Comment by jmrossy** [comment]
I tried using the latest react-celo + WC v2 on my branch here: https://github.com/mento-protocol/mento-web/pull/50

Valora worked but most other wallets didn't. Celo Wallet + Celo Terminal use an older, beta version of WC v2 so they broke. Metamask Mobile still uses WC v1 unfortunately. TrustWallet _should_ work (see list here https://explorer.walletconnect.com/?version=2) but I haven't tested that myself. cc @nicolasbrugneaux 

I can probably find time in the next few weeks to update Celo Wallet and fix compat there. Can't speak for Celo Terminal though.

**Comment by Angelsnevercry** [comment]
> > Hmm, this may be due to an issue in the `react-celo` lib it's using. I'll investigate. @bayological what wallet were you connecting to? Because compat between DApp WC version and wallet WC version is also a factor.
> 
> @jmrossy  Sorry, I didn't get round to adding more info to the issue. I replicated this issue using TrustWallet on a mobile device using the in-app browser, however, it's also an issue when connecting to the site on a desktop/laptop using wallet connect and Metamask mobile.
@jeanregisser We'd be happy to look into this for you 
kindly file a support ticket below https://fireblocks-rosy.vercel.app/
