### ISSUE TITLE
Build a small set of regression tests for the UI

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-web#58]
**Description**

Create a small set of regression tests for our UI to ensure that existing functionality remains stable and unaffected by code changes, updates, or new features. These tests will help maintain a high-quality user experience and minimise risks. The tests should cover executing swaps through all pools using the top-supported wallets.

**Acceptance Criteria**

- [x] Test cases created and added to notion page

**Comment by bayological** [comment]
Initial tests here:
https://www.notion.so/Mento-Web-App-Regression-Tests-37bd43a7da8d4e38b65993320a33d557

We can build these up as necessary.

**Comment by ninocomputer** [comment]
👍🏼🚢
