### ISSUE TITLE
Implement mento.org landing page redesign

### ISSUE THREAD

**Issue by ole-nov** [mento-protocol/mento-web#62]
***Description***

As part of Mento brand launch we are giving a fresh look to our website.

***Acceptance criteria***
- Light theme is developed according to [the design specs](https://www.figma.com/file/C2ilkEVASAPwejZlo3sRSb/Mento-2023-Landing%2C-Platform?type=design&node-id=90%3A2&t=f1cteeJSIVTQwsAe-1) and ready to be deployed.

@bayological to add tech acceptance criteria (like which tech stack should we use for landing and all of the web app)

**Comment by jmrossy** [comment]
@ole-nov This is the repo for the mento web app, not the landing page. Did you mean https://github.com/mento-protocol/mento-landing?

**Comment by olenovyk** [comment]
Thanks for pointing this out, I'll move to another repo!

**Comment by bayological** [comment]
Closed and re-created https://github.com/mento-protocol/mento-landing/issues/7
