### ISSUE TITLE
Make the mento.org landing page responsive

### ISSUE THREAD

**Issue by ole-nov** [mento-protocol/mento-web#63]
***Description***

As part of Mento brand launch we are giving a fresh look to our website.

***Acceptance criteria***
- Make the designs implemented in #392 responsive according to [the design specs](https://www.figma.com/file/C2ilkEVASAPwejZlo3sRSb/Mento-2023-Landing%2C-Platform?type=design&node-id=90%3A2&t=f1cteeJSIVTQwsAe-1) and ready to be deployed.

**Comment by bayological** [comment]
Recreated in correct repo. 

https://github.com/mento-protocol/mento-landing/issues/8
