### ISSUE TITLE
Update UI to add support for eXOF on Alfajores

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-web#71]
**Description**

We need to add eXOF & axlEUROC to the UI and make changes to allow swapping between them 

Configuration:
- Configure Token Mapping Add eXOF and axlEUROC to token list
- Configure eXOF and axlEUROC default state (0)
- Add & set eXOF and axlEUROC Icons
- Update the list of bipoolmanager exchanges to add the new pools (currently hardcoded somewhere in a config file)

Swap:
- Add eXOF and axlEUROC to swap form token list

  Other:
- Update website meta description to display eXOF in the list of stable available?

[Function](https://github.com/mento-protocol/mento-web/blob/8ea2a35226dad238ce3833832447a19decbb3c97/src/features/swap/SwapForm.tsx#L103) that sets output token to cUSD if input token is USDC variant

**Acceptance Criteria**

eXOF and axlEUROC can be chosen as tokens in the token lists  . When either axlEUROC or eXOF is chosen, the opposite token input field should default to the opposite token. e.g. When eXOF is chosen for input, the output should change to axlEUROC, and vice versa.  We can swap between axlEUROC and eXOF

**Comment by nvtaveras** [comment]
This was already done on Baklava, so this task will only be for doing it on Alfajores once it's deployed there. Mainnet will be done in a separate issue.
