### ISSUE TITLE
Add Bogdan and Markus's Twitter links to the mentolabs team page

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-web#86]
https://twitter.com/boqdan_
https://twitter.com/MarkusMento

**Comment by jmrossy** [comment]
@bowd I believe you're looking for the https://github.com/mento-protocol/mento-labs-landing repo here :)

**Comment by philbow61** [comment]
https://github.com/mento-protocol/mento-labs-landing/pull/13/files
