### ISSUE TITLE
Replace lottie animations in favor of something more efficient 

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/mento-web#92]
**Description**

While the Lottie format animations we're using for the swap confirmation are small, the library used to display them is pretty large. As suggested by @jmrossy, it may be a good idea to swap this out for a solution smaller in size and less complex. 

size of the current solution: 377K
 library lottie-react (315k, gzipped 79k) 
 62k each animation (31K each animation)

**Acceptance Criteria**

- [ ] A solution to display swap loading animations that is smaller in size

**Comment by RyRy79261** [comment]
Could just implement the loaders in css
