### ISSUE TITLE
Use Max Functionality Incorrectly Sets Output Value After Typing in Output Field

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/mento-web#93]
**Issue Description**:

When using our token swap interface, users can input desired output in the 'output' field to determine the necessary 'input,' or vice versa. However, if a user types a value into the 'output' field and clicks 'use max,' the system mistakenly sets the 'output' field to the maximum number of 'input' tokens. Essentially, it misinterprets the 'output' as the current 'input' because of the recent typing action in that field. The expected behavior should be that the 'use max' functionality sets the 'input' field to the maximum available tokens, irrespective of where the user has previously typed.

**Acceptance Criteria**:

- [ ] When a user types into the 'output' field and then clicks on the 'use max' button, the system should **NOT** change the value of the 'output' field based on the 'input' tokens.
- [ ] The 'use max' functionality should consistently set the 'input' field to the maximum available tokens, regardless of where the user has recently typed.

**Comment by gabrieltemtsen** [comment]
Please can you assign this to me ?

**Comment by gabrieltemtsen** [comment]
Hi @bayological
