### ISSUE TITLE
UI support for MU03 on test nets

### ISSUE THREAD

**Issue by philbow61** [mento-protocol/mento-web#98]
**Description**
For MU03 the UI needs to be updated to support new exchanges. 
Namely, USDC/cBRL, USDC/cEUR and EUROC/cEUR

**Acceptance Criteria**
- [x] UI allows users to swap via the new exchanges on Baklava
- [x] UI allows users to swap via the new exchanges on Alfajores

**Comment by denviljclarke** [comment]
I created a separate issue for the main net version of these changes here #100
